### ISSUE TITLE
Does plantnet support retrieving images and historical images given geographic boundaries?

### ISSUE THREAD

**Issue by bright1993ff66** [plantnet/my.plantnet#10]
Hi, thanks so much for developing such a great tutorial about the pl@ntnet API 😄 

I am new to pl@ntnet and have just registered one API code. I am trying to find some resources about downloading some images (preferably with species information and geo-tag) given a geographic boundary. I found the [Pl@ntnet Geo BETA](https://identify.plantnet.org/prediction) quite suit my needs. 

![image](https://github.com/user-attachments/assets/ed8370ff-4a99-4673-aa6e-bb97776b831d)

However, I still have some questions as below:

1. Does the pl@ntnet API support such a function? Does giving a coordinate boundary return a list of species within the boundary?
2. Can I access the historical data given one geographic boundary?

Thank you for your time!

**Comment by matcho** [comment]
Hi,

Please note that the GeoPl@ntNet interface you're using here is giving **predictions** of species presence in an area, it's not extracting actual occurrences from the Pl@ntNet dataset.

Neither of those features are supported by the Pl@ntNet API at this time, but they might be in the future.

Finally, we don't have historical data given a geographical boundary.

To better fit your needs, we suggest that you use the GBIF to retrieve Pl@ntNet data, through our published datasets : https://www.gbif.org/dataset/search?publishing_org=da86174a-a605-43a4-a5e8-53d484152cd3

Hope this helps,
Greetings,

The Pl@ntNet team
