### ISSUE TITLE
Filtering/sorting/paging for the species endpoint

### ISSUE THREAD

**Issue by mattosaurus** [plantnet/my.plantnet#8]
Hi, apologies if this is the wrong repo but I couldn't find one for the actual API.

Currently the `/v2/species` endpoint is effectively unuasable as it seems to return every single species (as expected). Would it be possible to implement some paging, filtering and sorting for this endpoint to make it more useable?

I'm imagining this would would be useful for functionanlity such as auto complete where it would search on the letters entered so far or to allow searching on particular species characteristics.

It would also be much more efficent for your servers as trying to return the entire species list has got to be pretty intensive.

**Comment by matcho** [comment]
Hi.

This is the wrong repo, but there's no public repo for Pl@ntNet API yet, so you did good :+1: 

Thank you for this suggestion, we'll consider adding this feature in the next developments.

**Comment by matcho** [comment]
Hi,

Routes `/v2/species` and `/v2/project/{project}/species` now support new parameters :
 * `pageSize`
 * `page`
 * `prefix`
 
edit: this will be deployed soon

**Comment by matcho** [comment]
Hi,
Pagination has been deployed:
 * https://my-api.plantnet.org/#/my-api/getV2ProjectsProjectSpecies
 * https://my-api.plantnet.org/#/my-api/getV2Species
 
Please note that pagination is disabled by default, for backwards compatibility reasons. You'll have to explicitly pass `page` and `pageSize` parameters.

**Comment by mattosaurus** [comment]
Nice, thanks for your speedy work 🙂
